---
    - name: Change hostname on CentOS7
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      command: hostnamectl set-hostname {{host_name}}
    
    - name: Change hostname on CentOS7
      when: ansible_distribution == "Amazon" 
      command: hostname set-hostname {{host_name}}


